[package]
name = "aoc_rust_22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
bit-vec = "0.6.3"
text_io = "0.1.12"